version: "3.3"
services:
  master:
    image: lizardfs-master
    build: 
      context: ./lizardfs-master
      args:
        - BASE_IMAGE=$BASE_IMAGE
    volumes:
      - ./volumes/lizardfs-master/etc/lizardfs:/etc/lizardfs/
      - ./volumes/lizardfs-master/var/lib/lizardfs/:/var/lib/lizardfs/
      - ./volumes/lizardfs-master/var/log/:/var/log/

  cgi:
    image: lizardfs-cgiserver
    build:
      context: ./lizardfs-cgiserver
      args:
        - BASE_IMAGE=$BASE_IMAGE
    ports:
      - "9425:9425"
    links:
      - master:mfsmaster
